### PR TITLE
Migrating to Bootstrap V5, dropping jQuery

### LINKED ISSUE #14: Updating to Bootstrap V5
Hi!

It's been a while since we transitioned to Bootstrap V4 (#3), and [Bootstrap Version 5 is coming right around the corner](https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/)! There's no rush to update, but it may be worth doing eventually. 

A quick sketch of what I think we'd need to investigate:
* Bootstrap is dropping jQuery, and I suggest we do the same. This does impact our approach to randomly generating the plugin cards, but it should be simple to replicate with vanilla JS!
* Bootstrap is now fully supporting RTL out of the box. If we make internationalization efforts in the future, this is helpful!
* There's a bit of renaming (some with the RTL change, some others) - we should make sure there are no collisions.

I'm more than happy to take a peek at this once the official release comes out (I think it's coming soon, beta-2 is almost done and I believe beta-3 will be the last). No rush to do anything until then, just wanted to put this on everyone's radar!

### PR DESCRIPTION
**Pull request by mattxwang**
Hello,

Bootstrap V5 stable was [just released today](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/). This PR swaps out *the minimum code possible* for us to switch to Bootstrap 5 (which no longer uses jQuery), but otherwise leaves the code untouched.

[You can preview the PR here](https://mattxwang.github.io/fiji.github.io/).

The big picture changes:

* updates Bootstrap's CSS, JS files to version 5
* removes jQuery as it's no longer needed
* uses Bootstrap's CDN to serve CSS/JS (instead of packaging it into the repo)
* updates the relevant code required to keep the site working (navbar, jumbotron, download button, plugins pane)

To quickly outline the code-focused migration changes:

* RTL support has changed directional utilities like `mr` for `margin-right` - changes those to `me` (margin end)
* `jumbotron` is removed; replaces it with the [utilities construction](https://getbootstrap.com/docs/5.0/examples/jumbotron/)
* changes all `$()` selector behaviour to use `document.getElementById`
* changes `$.get` to use `fetch()`
* uses the new `data-bs-*` js actions for the download dropdown, plugins pane 
* swaps `.sr-only` to `.visually-hidden`
* adds `aria-label` and `role` attributes when desired
* changes nav to use new form controls for search bar/input

I also noticed that the search bar doesn't work properly for me, but this issue is also on the live site for me - so I don't think that's a regression in this PR.

Let me know what y'all think! More than happy to swap things around, and there's no rush - Bootstrap did *just* release the stable v5!

(closes #14).

### CODE REVIEW

**Comment by ctrueden** [comment]
Wow, thanks @mattxwang! It doesn't sound like there's any reason to wait merging this, as long as you're confident everything (that worked previously) is still working. Right?

By the way: have you checked out https://imagej.github.io? We're nearly done rebuilding the ImageJ wiki in GitHub Pages. As part of that, we are in the process of integrating some parts of this fiji.sc splash site onto the imagej.github.io (which will become imagej.net when we reach production stage) front page. Not sure what the long-term fate of this fiji.sc splash page will be; it might make sense to make some changes to better integrate it with the content at https://imagej.github.io/fiji? Not sure yet. Suggestions and ideas welcome.

**Comment by mattxwang** [comment]
Oops, sorry for the late turnaround - been a hectic week!

> It doesn't sound like there's any reason to wait merging this, as long as you're confident everything (that worked previously) is still working. Right?

I believe everything is still working! I manually tested the download dropdown, the plugin pane, and the mobile nav, which are the only components of the site that rely on JS. I tested on Chrome/Firefox on macOS, so YMMV?

> By the way: have you checked out https://imagej.github.io?

Oh, I have not, but this looks cool! Very exciting, especially giving the wiki a facelift 😊 

As for integrating the content on this page, I think long-term it may make sense (though I'm curious, what would you do with the `fiji.sc` domain?). If that is the case, I'm happy to see what I can do to help with that as well.

**Comment by ctrueden** [comment]
> I'm curious, what would you do with the fiji.sc domain?

@mattxwang I think we want to continue serving a front-facing site about Fiji from this domain, although I suppose we could instead just do a simple redirect. As a software engineer, of course I don't like maintaining "duplicate" content, but the reality is that ImageJ and Fiji are two different-but-related "brands" and both sites probably need to continue existing. But we're certainly in the process of stealing the cool stuff from the fiji.sc front page for use on the imagej.net front page—particularly the featured plugins block.

**Comment by mattxwang** [comment]
That sounds like a good plan to me, the branding dilemma makes sense.

> But we're certainly in the process of stealing the cool stuff from the fiji.sc front page for use on the imagej.net front page—particularly the featured plugins block.

Glad to see it's being used elsewhere! Do let me know if you need any help migrating that over, hopefully this PR (removing jQuery) makes that even easier 😊

**Pull request merged**
