### PR TITLE
Issue 9: Replaced "navigator.appVersion" with "navigator.userAgent" i…

### LINKED ISSUE #9: Client OS not properly identified by javascript for download option.
In some cases (Firefox for Ubuntu Linux) the OS is not recognized and the user gets "Fiji is not currently supported on your OS" message.
A discussion of this problem can also be found on the forum at https://forum.image.sc/t/fiji-sc-website-greets-with-fiji-doesnt-currently-support-your-os-on-supported-os/26239.

### PR DESCRIPTION
**Pull request by turekg**
This should fix the problem with some OS information not being picked up by the download script.

Closes #9.

### CODE REVIEW

**Comment by carandraug** [comment]
Indeed, appVersion should not be the place to look for OS information. The [standards](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-appversion):

> appVersion: Must return either the string "4.0" or a string representing the version of the browser in detail, e.g. "1.0 (VMS; en-US) Mellblomenator/9000".

but instead of `userAgent`, maybe `platform` is more specific? From the [standards](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-platform):

> platform: Must return either the empty string or a string representing the platform on which the browser is executing, e.g. "MacIntel", "Win32", "FreeBSD i386", "WebTV OS".

**Comment by ctrueden** [comment]
Thanks @carandraug.

@turekg Could you please test out using `platform` on all supported platforms, and see whether that is effective?

**Comment by turekg** [comment]
Tested and confirmed that "platform" is an even better solution, code updated.

**Comment by carandraug** [comment]
7cba001 replaces `userAgent` with `platform` for windows only. In the case of Mac and Linux, it still checks `userAgent`. Was that on purpose?

**Comment by ctrueden** [comment]
@carandraug Thanks for catching that. Fixed in 47ae7fdf09ab9322f1b26aae551960d4ee2af7e9.

**Pull request merged**
