### PR TITLE
CHANGED TITLE

### PR DESCRIPTION
**Pull request by Sweltron**

### CODE REVIEW

**Comment by dscho** [comment]
Is this PR the result of one of those class assignments where you have to get a PR approved by an open source project? If so, you will have to figure out how to _actually_ improve anything. Opening PRs just for opening's sake is not helpful at all.

**Comment by haesleinhuepf** [comment]
I think that might be the first PR submitted by a bot I've ever seen. 😁

**Comment by dscho** [comment]
@haesleinhuepf I've seen similar PRs crop up in the Git for Windows project. Apparently, there is a teacher who makes it a mandatory assignment to get a PR merged into an open source project, but not mandatory that that PR actually make sense. I would wager a bet that we're encountering that case here, too.

**Comment by dscho** [comment]
Oh. It's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) season. Expect many PRs like this one.

**Comment by miura** [comment]
I find happiness. Happiness does not find me.

**Comment by ctrueden** [comment]
I saw my first spam PR the other day. As in: actual link spamming. I reported it as spam, but it does not seem to be possible to actually delete it. I hope we are not entering a brave new era of GitHub spam. We've been very fortunate for the past few years to have in GitHub a development platform with extremely high signal to noise.

**Pull request closed without merging**
